name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v0.1.0

jobs:
  build:
    name: Build Provider
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          # Build binary for the target OS/arch
          OUTPUT_NAME="terraform-provider-quote_${GOOS}_${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            OUTPUT_NAME="${OUTPUT_NAME}.exe"
          fi
          
          go build -o $OUTPUT_NAME
          
          # Zip the binary
          zip "${OUTPUT_NAME}.zip" $OUTPUT_NAME

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            terraform-provider-quote_*.zip
