name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on semantic version tags (e.g. v0.1.0)

# Required permissions to create releases
permissions:
  contents: write

jobs:
  build:
    name: Build Provider
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Inherit and reinforce permissions
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for release notes

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          # Generate output filename
          if [ "$GOOS" = "windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi
          OUTPUT="terraform-provider-quote_${GOOS}_${GOARCH}${EXT}"

          # Build binary
          go build -o $OUTPUT

          # Create ZIP archive
          if [ "$GOOS" = "windows" ]; then
            zip "${OUTPUT}.zip" $OUTPUT
          else
            tar -czvf "${OUTPUT}.tar.gz" $OUTPUT
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use default token or your PAT
        with:
          files: |
            terraform-provider-quote_*
